{
    "addition": {
        "26": "import com.google.errorprone.annotations.CanIgnoreReturnValue;\n",
        "99": "    InvocationHandler handler =\n",
        "100": "        new InvocationHandler() {\n",
        "102": "          public Object invoke(Object obj, final Method method, final Object[] args)\n",
        "103": "              throws Throwable {\n",
        "104": "            Callable<Object> callable =\n",
        "105": "                new Callable<Object>() {\n",
        "106": "                  @Override\n",
        "107": "                  public Object call() throws Exception {\n",
        "108": "                    try {\n",
        "109": "                      return method.invoke(target, args);\n",
        "110": "                    } catch (InvocationTargetException e) {\n",
        "111": "                      throw throwCause(e, false);\n",
        "112": "                    }\n",
        "113": "                  }\n",
        "114": "                };\n",
        "115": "            return callWithTimeout(\n",
        "116": "                callable, timeoutDuration, timeoutUnit, interruptibleMethods.contains(method));\n",
        "123": "  @CanIgnoreReturnValue\n",
        "125": "  public <T> T callWithTimeout(\n",
        "126": "      Callable<T> callable, long timeoutDuration, TimeUnit timeoutUnit, boolean amInterruptible)\n",
        "127": "      throws Exception {\n"
    },
    "removed": {
        "98": "    InvocationHandler handler = new InvocationHandler() {\n",
        "99": "      @Override\n",
        "100": "      public Object invoke(Object obj, final Method method, final Object[] args)\n",
        "101": "          throws Throwable {\n",
        "102": "        Callable<Object> callable = new Callable<Object>() {\n",
        "104": "          public Object call() throws Exception {\n",
        "105": "            try {\n",
        "106": "              return method.invoke(target, args);\n",
        "107": "            } catch (InvocationTargetException e) {\n",
        "108": "              throwCause(e, false);\n",
        "109": "              throw new AssertionError(\"can't get here\");\n",
        "110": "            }\n",
        "113": "        return callWithTimeout(callable, timeoutDuration, timeoutUnit,\n",
        "114": "            interruptibleMethods.contains(method));\n",
        "115": "      }\n",
        "116": "    };\n",
        "122": "  public <T> T callWithTimeout(Callable<T> callable, long timeoutDuration,\n",
        "123": "      TimeUnit timeoutUnit, boolean amInterruptible) throws Exception {\n"
    }
}