{
    "addition": {},
    "removed": {
        "1641": "public void testDereference_genericsHierarchy() throws Exception {\n",
        "1642": "  com.google.common.util.concurrent.FuturesTest testCase = new com.google.common.util.concurrent.FuturesTest();\n",
        "1643": "  testCase.setUp();\n",
        "1644": "  Throwable failure = null;\n",
        "1645": "  try {\n",
        "1646": "    testCase.testDereference_genericsHierarchy();\n",
        "1647": "  } catch (Throwable t) {\n",
        "1648": "    failure = t;\n",
        "1649": "  }\n",
        "1650": "  try {\n",
        "1651": "    testCase.tearDown();\n",
        "1652": "  } catch (Throwable t) {\n",
        "1653": "    if (failure == null) {\n",
        "1654": "      failure = t;\n",
        "1655": "    }\n",
        "1656": "  }\n",
        "1657": "  if (failure instanceof Exception) {\n",
        "1658": "    throw (Exception) failure;\n",
        "1659": "  }\n",
        "1660": "  if (failure instanceof Error) {\n",
        "1661": "    throw (Error) failure;\n",
        "1662": "  }\n",
        "1663": "  if (failure != null) {\n",
        "1664": "    throw new RuntimeException(failure);\n",
        "1665": "  }\n",
        "1666": "}\n",
        "1667": "\n",
        "1668": "public void testDereference_genericsWildcard() throws Exception {\n",
        "1669": "  com.google.common.util.concurrent.FuturesTest testCase = new com.google.common.util.concurrent.FuturesTest();\n",
        "1670": "  testCase.setUp();\n",
        "1671": "  Throwable failure = null;\n",
        "1672": "  try {\n",
        "1673": "    testCase.testDereference_genericsWildcard();\n",
        "1674": "  } catch (Throwable t) {\n",
        "1675": "    failure = t;\n",
        "1676": "  }\n",
        "1677": "  try {\n",
        "1678": "    testCase.tearDown();\n",
        "1679": "  } catch (Throwable t) {\n",
        "1680": "    if (failure == null) {\n",
        "1681": "      failure = t;\n",
        "1682": "    }\n",
        "1683": "  }\n",
        "1684": "  if (failure instanceof Exception) {\n",
        "1685": "    throw (Exception) failure;\n",
        "1686": "  }\n",
        "1687": "  if (failure instanceof Error) {\n",
        "1688": "    throw (Error) failure;\n",
        "1689": "  }\n",
        "1690": "  if (failure != null) {\n",
        "1691": "    throw new RuntimeException(failure);\n",
        "1692": "  }\n",
        "1693": "}\n",
        "1694": "\n",
        "1695": "public void testDereference_innerCancelsResult() throws Exception {\n",
        "1696": "  com.google.common.util.concurrent.FuturesTest testCase = new com.google.common.util.concurrent.FuturesTest();\n",
        "1697": "  testCase.setUp();\n",
        "1698": "  Throwable failure = null;\n",
        "1699": "  try {\n",
        "1700": "    testCase.testDereference_innerCancelsResult();\n",
        "1701": "  } catch (Throwable t) {\n",
        "1702": "    failure = t;\n",
        "1703": "  }\n",
        "1704": "  try {\n",
        "1705": "    testCase.tearDown();\n",
        "1706": "  } catch (Throwable t) {\n",
        "1707": "    if (failure == null) {\n",
        "1708": "      failure = t;\n",
        "1709": "    }\n",
        "1710": "  }\n",
        "1711": "  if (failure instanceof Exception) {\n",
        "1712": "    throw (Exception) failure;\n",
        "1713": "  }\n",
        "1714": "  if (failure instanceof Error) {\n",
        "1715": "    throw (Error) failure;\n",
        "1716": "  }\n",
        "1717": "  if (failure != null) {\n",
        "1718": "    throw new RuntimeException(failure);\n",
        "1719": "  }\n",
        "1720": "}\n",
        "1721": "\n",
        "1722": "public void testDereference_outerCancelsResult() throws Exception {\n",
        "1723": "  com.google.common.util.concurrent.FuturesTest testCase = new com.google.common.util.concurrent.FuturesTest();\n",
        "1724": "  testCase.setUp();\n",
        "1725": "  Throwable failure = null;\n",
        "1726": "  try {\n",
        "1727": "    testCase.testDereference_outerCancelsResult();\n",
        "1728": "  } catch (Throwable t) {\n",
        "1729": "    failure = t;\n",
        "1730": "  }\n",
        "1731": "  try {\n",
        "1732": "    testCase.tearDown();\n",
        "1733": "  } catch (Throwable t) {\n",
        "1734": "    if (failure == null) {\n",
        "1735": "      failure = t;\n",
        "1736": "    }\n",
        "1737": "  }\n",
        "1738": "  if (failure instanceof Exception) {\n",
        "1739": "    throw (Exception) failure;\n",
        "1740": "  }\n",
        "1741": "  if (failure instanceof Error) {\n",
        "1742": "    throw (Error) failure;\n",
        "1743": "  }\n",
        "1744": "  if (failure != null) {\n",
        "1745": "    throw new RuntimeException(failure);\n",
        "1746": "  }\n",
        "1747": "}\n",
        "1748": "\n",
        "1749": "public void testDereference_resultCancelsInner() throws Exception {\n",
        "1750": "  com.google.common.util.concurrent.FuturesTest testCase = new com.google.common.util.concurrent.FuturesTest();\n",
        "1751": "  testCase.setUp();\n",
        "1752": "  Throwable failure = null;\n",
        "1753": "  try {\n",
        "1754": "    testCase.testDereference_resultCancelsInner();\n",
        "1755": "  } catch (Throwable t) {\n",
        "1756": "    failure = t;\n",
        "1757": "  }\n",
        "1758": "  try {\n",
        "1759": "    testCase.tearDown();\n",
        "1760": "  } catch (Throwable t) {\n",
        "1761": "    if (failure == null) {\n",
        "1762": "      failure = t;\n",
        "1763": "    }\n",
        "1764": "  }\n",
        "1765": "  if (failure instanceof Exception) {\n",
        "1766": "    throw (Exception) failure;\n",
        "1767": "  }\n",
        "1768": "  if (failure instanceof Error) {\n",
        "1769": "    throw (Error) failure;\n",
        "1770": "  }\n",
        "1771": "  if (failure != null) {\n",
        "1772": "    throw new RuntimeException(failure);\n",
        "1773": "  }\n",
        "1774": "}\n",
        "1775": "\n",
        "1776": "public void testDereference_resultCancelsOuter() throws Exception {\n",
        "1777": "  com.google.common.util.concurrent.FuturesTest testCase = new com.google.common.util.concurrent.FuturesTest();\n",
        "1778": "  testCase.setUp();\n",
        "1779": "  Throwable failure = null;\n",
        "1780": "  try {\n",
        "1781": "    testCase.testDereference_resultCancelsOuter();\n",
        "1782": "  } catch (Throwable t) {\n",
        "1783": "    failure = t;\n",
        "1784": "  }\n",
        "1785": "  try {\n",
        "1786": "    testCase.tearDown();\n",
        "1787": "  } catch (Throwable t) {\n",
        "1788": "    if (failure == null) {\n",
        "1789": "      failure = t;\n",
        "1790": "    }\n",
        "1791": "  }\n",
        "1792": "  if (failure instanceof Exception) {\n",
        "1793": "    throw (Exception) failure;\n",
        "1794": "  }\n",
        "1795": "  if (failure instanceof Error) {\n",
        "1796": "    throw (Error) failure;\n",
        "1797": "  }\n",
        "1798": "  if (failure != null) {\n",
        "1799": "    throw new RuntimeException(failure);\n",
        "1800": "  }\n",
        "1801": "}\n",
        "1802": "\n"
    }
}